language: node_js
sudo: false
node_js:
  - "8.11.1"
install:
  - npm install
#script:
#- npm test
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: "67519e8f-950b-41a9-9a68-df14f2eaf67f"
  app: claro-brasil-backend-nodejs
